require:
  - standard/cop/block_single_line_braces
  - ruby-next/rubocop

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rubocop_rspec.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'lib/.rbnext/**/*'
    - 'lib/generators/**/templates/*.rb'
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: disable
  TargetRubyVersion: next

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Lint/RedundantRequireStatement:
  Enabled: false

Lint/ItWithoutArgumentsInBlock:
  Enabled: false

# Doesn't work in Ruby 3.3.0 https://bugs.ruby-lang.org/issues/20090
Style/ArgumentsForwarding:
  Enabled: false

Style/ItBlockParameter:
  Enabled: false
