require:
  - standard/cop/semantic_blocks
  - rubocop-md

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.5

Standard/SemanticBlocks:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

Lint/Void:
  Exclude:
    - '**/*.md'


Lint/DuplicateMethods:
  Exclude:
    - '**/*.md'

Naming/FileName:
  Exclude:
   - '**/*.md'

Layout/InitialIndentation:
  Exclude:
    - 'CHANGELOG.md'
