require:
  - standard/cop/semantic_blocks
  - ruby-next/rubocop

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'lib/.rbnext/**/*'
    - 'lib/generators/**/templates/*.rb'
  DisplayCopNames: true
  TargetRubyVersion: next

Standard/SemanticBlocks:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

